name: offlinetodo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.0.0-dev.9
  flutter_data: ^1.4.7
  flutter_riverpod: ^1.0.3
  json_annotation: ^4.5.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
